### PR TITLE
Override Stupid Light Blue colours

### PR DESCRIPTION
**Pull request by ygt-mikekchar**
Stupidly reusing an old branch by accident.

@ygt-luca I started getting the same colour problems as you (with the super light blue text that you can't read in Agnostic light).  I finally tracked it down to one of the packages was setting several colours to 256 colour values.  I didn't actually figure out what package it was, but the result was that it was picking really strange colours because we are in 16 colour mode.

I think I have mostly fixed the problem by explicitly setting the ones that that I could find.  I don't know if these are good colours, so please give it a try.

The one other thing I did was explicitly set the background for Error and TODO because again some stupid package is setting the background to red and since the text is red, it ends up being unreadable.  So instead, I set the background to light red and the foreground to whatever the normal text foreground is.

I have a few more things to do (including a new set of colours for Agnostic Light which have better contrast), but I will submit them as seperate PRs over the next couple of days.

### CODE REVIEW

**Comment by ygt-luca** [comment]
Hi Mike, thanks for this, it's very good news that you are doing this :)

Here's a screenshot of what I get in iterm... keep in mind that I had to recreate the terminal palette manually, so I may have done some mistake... :(

screen shot 2015-01-07 at 07 19 14

**Comment by ygt-luca** [comment]
here are the palettes by the way, for you to check:

screen shot 2015-01-07 at 07 27 19
screen shot 2015-01-07 at 07 27 29

**Comment by ygt-mikekchar** [comment]
The documentation hilighting doesn't look too good with gray on dark backgrounds.  However, I don't seem to be able to get that hilighting... what hiliting mode is it using?  Probably I need to override some more settings.

Also, can profiles be imported into iTerm2? I would be happy to give you an automated way of setting them if possible :-)

**Comment by ygt-mikekchar** [comment]
Ah... Here is an example of one: https://github.com/hardcore/iTerm-colors

I will put it on my todo list.

**Comment by ygt-luca** [comment]
Hey there!
The highlighting that you noticed is the spell checking activated on the
vanilla agnostic.
As to colours, I created the palettes manually (it's possible to enter
hexadecimal colours directly despite what the interwebs say), but they can
exported individually, which I did and they are in my public dotfiles. It's
not exactly the same as setting programmatically, but still useful as a
temporary measure...

**Comment by ygt-mikekchar** [comment]
Ah cool!  I will make spellchecking highlighting a priority!  Thanks! :-)

**Comment by ygt-mikekchar** [comment]
I want to do some work on colour themes and would like to defer doing the PMenu and spell stuff until later, so I'm going to merge this PR as it is for now.

**Pull request merged**
